"""add live-url

Revision ID: 7ea8706f8543
Revises: cbff26ee7e21
Create Date: 2019-04-17 16:25:39.395157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea8706f8543'
down_revision = 'cbff26ee7e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live', sa.Column('live_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live', 'live_url')
    # ### end Alembic commands ###
